# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust

# IPv4 local connections:
host    all             all             127.0.0.1/32            trust

# IPv6 local connections:
host    all             all             ::1/128                 trust

# Allow any user from any host to connect to any DB (Fine for local dev)
host    all             all             0.0.0.0/0               md5

# ALLOW REPLICATION CONNECTIONS (The fix)
host    replication     all             0.0.0.0/0               trust