[pytest]
DJANGO_SETTINGS_MODULE = config.settings
# Tell pytest where to look for tests
python_files = tests.py test_*.py *_tests.py
# Tell pytest-asyncio to automatically treat async def as async tests
asyncio_mode = auto